# Azimutec/KikundiBundle/Resources/config/config.yml

# Assetic Configuration
# on enleve cette ligne car "prepend"
#assetic:
debug: '%kernel.debug%'
use_controller: '%kernel.debug%'
bundles: [AzimutecKikundiBundle]
#java: /usr/bin/java
filters:
    cssrewrite: ~
    #closure:
    #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
    #yui_css:
    #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

assets:
    font-awesome-eot:
        inputs: '@AzimutecKikundiBundle/Resources/public/fonts/fontawesome/fontawesome-webfont.eot'
        output: 'fonts/fontawesome/fontawesome-webfont.eot'
    font-awesome-svg:
        inputs: '@AzimutecKikundiBundle/Resources/public/fonts/fontawesome/fontawesome-webfont.svg'
        output: 'fonts/fontawesome/fontawesome-webfont.svg'
    font-awesome-ttf:
        inputs: '@AzimutecKikundiBundle/Resources/public/fonts/fontawesome/fontawesome-webfont.ttf'
        output: 'fonts/fontawesome/fontawesome-webfont.ttf'
    font-awesome-woff:
        inputs: '@AzimutecKikundiBundle/Resources/public/fonts/fontawesome/fontawesome-webfont.woff'
        output: 'fonts/fontawesome/fontawesome-webfont.woff'
    font-awesome-woff2:
        inputs: '@AzimutecKikundiBundle/Resources/public/fonts/fontawesome/fontawesome-webfont.woff2'
        output: 'fonts/fontawesome/fontawesome-webfont.woff2'
